owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Rovergulf Dev Auth API
    url: https://api-dev.rovergulf.net/auth/health
  - name: Rovergulf Dev Core API
    url: https://api-dev.rovergulf.net/engine/health
  - name: Rovergulf Dev Media API
    url: https://api-dev.rovergulf.net/media/health
  - name: Rovergulf Dev Events API
    url: https://api-dev.rovergulf.net/events/health

status-website:
  cname: status.rovergulf.net
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/56350485?s=400&u=4edbcfa8024d85b7f6745ead98c97778bf291034&v=4
  name: Rovergulf Operations - API Status
  introTitle: "Rovergulf Engineers Services Status"
  introMessage: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
